### ISSUE TITLE
Accessories : using it without hiddent ducks

### ISSUE THREAD

**Issue by maieul** [samcarter8/tikzmarmots#1]
Thanks for this really useful new package!

Actually, to add accessories, we must add invisible ducks.

May I suggest an other code organization 
- one main module, call "animal-accessories" which define the accessorie
- many other module which define animal themself (ducks, marmot etc) and use the main module for accessories.

That could allow use to do something like \marmot[signpost=XX]

**Comment by samcarter8** [comment]
Thanks a lot for your feedback! 

This would indeed be a great improvement and make things much easier to use. I will keep it in mind, but I am afraid that I probably won't have time in the next few month - some real life work to finish...

------

A short explanation for the current concept:

All the accessories where designed with the ducks in mind. Some can easily be re-used, some would need to be adjusted as they are shaped and positioned to be used with the ducks. If I'd enable direct usage via `\marmot[signpost=XX]` I would feel responsible that all the accessories are positioned and adjusted to fit the marmots (or any other tikz species), which is something I currently cannot provide.

**Comment by samcarter8** [comment]
This issue will be addressed in the up-coming [tikzlings](https://github.com/samcarter8/tikzlings) package. All tikzlings, including the marmot, are sharing a common library of items. 

In principle this is already working, but at the moment there are not yet many items available:

```
\documentclass{standalone}
\usepackage{tikzlings}

\begin{document}
	
\begin{tikzpicture}
	\marmot[crown]
\end{tikzpicture}	
	
\end{document}
```
![document](https://user-images.githubusercontent.com/8226363/45220114-6d70de80-b2ad-11e8-9fb2-c431da51d17a.png)
